### ISSUE TITLE
Add files to private folder?

### ISSUE THREAD

**Issue by jadsonlourenco** [nourharidy/meteor-ssl#1]
You tell on documentation to put file on **private** folder, but how I can pass this argument on ```SSL()``` function? You can show an example? 

I try with http://docs.meteor.com/#/full/assets_getText but not work.

Thanks!

**Comment by nourharidy** [comment]
The documentation is quite clear: you should put the absolute path to both files, whether inside the private folder or somewhere else, for example:
SSL('/home/user/meteorapp/private/server.key', 'home/user/meterapp/private/server.crt')

**Comment by jadsonlourenco** [comment]
Ok man, but with example is better to understand you think. Thank you!

**Comment by nourharidy** [comment]
Indeed, i have added an example to the documentation.

**Comment by marcoroche** [comment]
On heroku server I added: SSL('/app/private/ssl.key','/app/private/ssl.crt', 443);
to reach the files.

**Comment by LAKnoKAL** [comment]
@nourharidy can I somehow use a relative path or maybe use some global NODE vars to concatenate it and get absolute path here? I just need to use the same dir inside the app(for example `private/localhost.key`) on few different machines.
