### ISSUE TITLE
Template is not defined

### ISSUE THREAD

**Issue by godadada** [nourharidy/meteor-ssl#18]
There may be a bug in meteor-ssl:
       ReferenceError: Template is not defined[Learn More] nourharidy_ssl.js:51:

The error location is here:
 line 15 of file  meteor-ssl/helpers.js

This may be similar to  the bug discovered in other's code:
https://stackoverflow.com/questions/37600166/referenceerror-template-is-not-defined-meteor

**Comment by godadada** [comment]
Here is partial solution:
http://forum.cleverbeagle.com/t/using-mjml-in-pup-and-ssl/189

**Comment by godadada** [comment]
Adding 'if (Meteor.isClient) {' to the issue code block may work according to this:
https://stackoverflow.com/questions/10442419/what-causes-template-is-not-defined-in-meteor

**Comment by nourharidy** [comment]
PR merged. Thank you for contributing!
