### ISSUE TITLE
Socket hangup

### ISSUE THREAD

**Issue by morrismukiri** [nourharidy/meteor-ssl#2]
I keep getting a socket hangup every now and then, after which the server restarts. Here's the error I'm getting

.meteor\packages\nourharidy_ssl\0.2.2\npm\node_modules\http-proxy\lib\http-proxy\index.js:119

> (STDERR)     throw err;
> (STDERR)           ^
> (STDERR) Error: socket hang up
> (STDERR)     at createHangUpError (http.js:1477:15)
> (STDERR)     at Socket.socketCloseListener (http.js:1527:23)
> (STDERR)     at Socket.emit (events.js:95:17)
> (STDERR)     at TCP.close (net.js:466:12)

**Comment by wdhif** [comment]
Same error here, also getting this :

```
/opt/icon/app/programs/server/npm/nourharidy_ssl/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketCloseListener (http.js:1527:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #40```

**Comment by sylido** [comment]
Having the same issue here, seems like it's Meteor 1.2 related since this was not happening before that.

**Comment by array-addu** [comment]
Does anyone found the solution to this?

**Comment by nourharidy** [comment]
Please report if this issue is still happening on Meteor 1.4.
I think this could be an incompatibility issue between this version of the npm http-proxy module and the node.js version of your meteor distribution.

**Comment by csillag** [comment]
It is still happening with Meteor 1.5

**Comment by sylido** [comment]
It is a problem with the http-proxy module, the fix was to override the package by just adding one line to detect if there is an error and `return`. Here's the file I created based off of the ones in this package -> https://pastebin.com/xNxNXPXg we never had hangups again, even if they happen they shouldn't affect the app.

**Comment by nourharidy** [comment]
@sylido 's solution has been committed to the repository. No need to override the SSL() function anymore.

**Comment by Slind14** [comment]
Unfortunately this is still an issue. Not as frequently as before, but still present.

**Comment by VikR0001** [comment]
I'm getting it on just about every re-build for some reason.
