### ISSUE TITLE
Documentation suggestion, dynamic private folder location

### ISSUE THREAD

**Issue by JulianKingman** [nourharidy/meteor-ssl#3]
I'm using docker on my server, so I don't want to hard code a value since it will be different on my localhost and on my server, so I suggest adding this to the documentation, it makes the location super simple, as you just put it in the private folder:
````javascript
var key = process.env.PWD + '/private/app_example_com.key';
var cert = process.env.PWD + '/private/app_example_com.crt';
SSL(key, cert, 443);
````

**Comment by athyuttamre** [comment]
This only works if you run `meteor` from the root directory of the app, yes? Otherwise `process.env.PWD` takes on the value of the directory from which meteor was run?

**Comment by JulianKingman** [comment]
I'm not sure, I don't know what it would mean to run the app outside of the root directory. How does that work?

**Comment by athyuttamre** [comment]
So turns out you can run `meteor` from any directory within the app's root directory. I guess if you're using Docker you'll be fine, but if I was to say `cd client` and then run `meteor`, the `process.env.PWD` would change and not support this code.

By itself, it's a good tip though!

**Comment by JulianKingman** [comment]
I see what you're saying now. Is there another dynamic variable that returns the root directory?

**Comment by athyuttamre** [comment]
Unfortunately not as far as I know.

**Comment by JulianKingman** [comment]
OK, then this would be as close are you can get. Thanks!

**Comment by athyuttamre** [comment]
By the way @JulianKingman, would you mind sharing your Dockerfile / docker-compose.yml in a gist? I'm trying to get it working on my app. :)

**Comment by JulianKingman** [comment]
Here you go :)
jwilder's nginx reverse proxy image makes it super easy.
https://gist.github.com/JulianKingman/dc2a22ee46eb27385f14

**Comment by athyuttamre** [comment]
Awesome, thanks @JulianKingman! The extra Mongo services seem really cool, and the free SSL would be awesome if it worked out. :smiley:

Here's the one I came up with: https://github.com/athyuttamre/signmeup/tree/docker. Definitely going to add some of your ideas, thank you!
