### ISSUE TITLE
SSL is no defined

### ISSUE THREAD

**Issue by xuecat** [nourharidy/meteor-ssl#4]
`Messages = new Mongo.Collection('messages');

Messages.allow({
  update: function(userId, message) { return true; },
  remove: function(userId, message) { return true; },
  insert: function(userId) { return true; }
});
Meteor.startup(function() {
    SSL('../../../../../private/server.key','../../../../../private/server.crt', 443);
});
`

what's wrong??????

**Comment by nourharidy** [comment]
Are you sure you're not running on the client side?

**Comment by Harish-Kommuri** [comment]
Add `declare var SSL: any;` at the top of the file.
