### ISSUE TITLE
Doesn't work without Blaze

### ISSUE THREAD

**Issue by twastvedt** [nourharidy/meteor-ssl#5]
I'm using angular2-meteor, which substitutes Angular 2 for Blaze templates. This package throws the following error: `Uncaught ReferenceError: Template is not defined`. I think all that is necessary is to add a check to the `Template.registerHelper` line. Is there a place to get the files so I could make this change, as this repository is empty?

**Comment by nourharidy** [comment]
The code has been uploaded. Please fork and PR as needed to fix the issue.

**Comment by JustFly1984** [comment]
Guys, have same issue with React.
